export const BUILDING_CLICK = "BUILDING_CLICK";
export const MODAL_HIDE = "MODAL_HIDE";
export const SEARCH_BUILDING_STATE = "SEARCH_BUILDING_STATE";
export const SEARCH_BUILDING_CLICK = "SEARCH_BUILDING_CLICK";
export const ZOOM_CHANGED = "ZOOM_CHANGED";
