/******** Map ********/
export const REQUEST_BUILDING = "REQUEST_BUILDING";
export const GET_BUILDING_SUCCESS = "GET_BUILDING_SUCCESS"
export const GET_BUILDING_FAILURE = "GET_BUILDING_FAILURE"
export const ZOOM_CHANGED = "ZOOM_CHANGED";
export const HIDE_MARKERS = "HIDE_MARKERS"

/******** SearchBar ********/
export const TOGGLE_SIDE_BAR = "TOGGLE_SIDE_BAR"

/******** SearchBar ********/
export const SEARCH_VALUE_CHANGE = "SEARCH_VALUE_CHANGE";
export const SEARCH = "SEARCH";

/******** Post ********/
export const REQUEST_BOARD = "REQUEST_BOARD"
export const GET_BOARD_SUCCESS = "GET_BOARD_SUCCESS"
export const GET_BOARD_FAILURE = "GET_BOARD_FAILURE"
export const REQUEST_POST = "REQUEST_POST"
export const GET_POST_SUCCESS = "GET_POST_SUCCESS"
export const GET_POST_FAILURE = "GET_POST_FAILURE"
export const SAVE_POST = "SAVE_POST";
export const SHOW_WRITE_POST = "SHOW_WRITE_POST";

/******** Restaurant ********/
export const TOGGLE_RES_MARKER = "TOGGLE_RES_MARKER"
export const REQUEST_RESTAURANT = "REQUEST_RESTAURANT";
export const GET_RESTAURANT_SUCCESS = "GET_RESTAURANT_SUCCESS";
export const GET_RESTAURANT_FAILURE = "GET_RESTAURANT_FAILURE";
export const REQUEST_ALL_RESTAURANTS = "REQUEST_ALL_RESTAURANTS";
export const GET_ALL_RESTAURANTS_SUCCESS = "GET_ALL_RESTAURANTS_SUCCESS";
export const GET_ALL_RESTAURANTS_FAILURE = "GET_ALL_RESTAURANTS_FAILURE";

/******** Seminar ********/
export const TOGGLE_SEMI_MARKER = "TOGGLE_SEMI_MARKER"
export const CHANGE_SEMINAR_PAGE = "CHANGE_SEMINAR_PAGE";
export const REQUEST_SEMINAR = "REQUEST_SEMINAR"
export const GET_SEMINAR_SUCCESS = "GET_SEMINAR_SUCCESS"
export const GET_SEMINAR_FAILURE = "GET_SEMINAR_FAILURE"
export const REQUEST_BLDG_SEMINARS = "REQUEST_BLDG_SEMINARS";
export const GET_BLDG_SEMINARS_SUCCESS = "GET_BLDG_SEMINARS_SUCCESS"
export const GET_BLDG_SEMINARS_FAILURE = "GET_BLDG_SEMINARS_FAILURE"
export const REQUEST_ALL_SEMINARS = "REQUEST_ALL_SEMINARS";
export const GET_ALL_SEMINARS_SUCCESS = "GET_ALL_SEMINARS_SUCCESS"
export const GET_ALL_SEMINARS_FAILURE = "GET_ALL_SEMINARS_FAILURE"
