export const BUILDING_CLICK = "BUILDING_CLICK";
export const MODAL_HIDE = "MODAL_HIDE";
export const SEARCH_VALUE_CHANGE = "SEARCH_VALUE_CHANGE";
export const SEARCH = "SEARCH";
export const ZOOM_CHANGED = "ZOOM_CHANGED";
